import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Evan Portfolio App",
  description: "Generated by create next app",
  icons: {
    icon: "/crayon-sinchan.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900 flex flex-col max-w-full">
        <Navbar />
        <main className="container mx-auto flex-grow">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
